### ISSUE TITLE
No version tagged in docker hub

### ISSUE THREAD

**Issue by beardypig** [blacktop/docker-ghidra#1]
Hi, thanks for the Docker image - super useful :D 

There is only a `:latest` tag in Docker Hub, is it possible to include `9.0` or similar tag?

Thanks!

**Comment by blacktop** [comment]
Sorry about that!  The fix I just pushed should now create :9.0 and :9 tags auto-magically. (should be ready shortly)

Thanks for letting me know 👍

**Comment by beardypig** [comment]
Nice, thanks for the quick response.
