### ISSUE TITLE
Docker Hub missing version 10 / 10.0.1

### ISSUE THREAD

**Issue by Montg0mery** [blacktop/docker-ghidra#13]
Docker Hub (https://hub.docker.com/r/blacktop/ghidra) is missing a tag for the version 10 branch, and the "latest" tag is pointing to 9.2.4.

I think this is because it is based off the `Dockerfile` file, whereas the only one that is being updated by @blacktop seems to be `Dockerfile.alpine`.

For people who have deployed the image from Docker Hub using the "latest" tag, they are not getting updated to the latest stable version when running `docker pull`, as it is stuck on 9.2.4.

Please let me know if I've misunderstood something.

**Comment by blacktop** [comment]
Thank you for brining this to my attention!  ~~I have swapped out the Dockerfile with the Dockerfile.alpine as the file read by the automated dockerhub builds.~~ Updated the non-alpine Dockerfile.  They are building now, feel free to close once you have noticed the correction work it's way through docker's servers

**Comment by Montg0mery** [comment]
@blacktop - that has fixed the issue with the `latest` tag, and an existing image now updates to 10.0.1 with `docker pull`. Thank you for the quick fix!

I see 2 other related issues with tags.

- The `9` tag is now pulling 10.0.1, whereas it should presumably stay with the latest version on the 9 branch
- There is no `10` tag available on Docker Hub (which should track the 10 branch but then not auto-update to the 11 branch when that comes out) - https://hub.docker.com/r/blacktop/ghidra/tags

That way people can pick a major branch (like 9, or 10) and have the images auto-update on a regular basis for minor patches, but not auto-update to the next major version (so that they can do more testing before updating, read the changelog etc.).

**Comment by blacktop** [comment]
Good catch!  It looks like Docker won't build my images anymore unless I give them $5 a month :'(. Might have to move the images to github

**Comment by ties** [comment]
> Good catch! It looks like Docker won't build my images anymore unless I give them $5 a month :'(. Might have to move the images to github

For what it is worth, my experience with building using github actions was that it was an easy migration. It worked out of the box when following the documentation (think I used https://docs.github.com/en/actions/guides/publishing-docker-images)

**Comment by blacktop** [comment]
@ties thank you for pointing me at that.  The github actions workflows are REALLY nice.  Hopefully microsoft can keep that service free unlike docker/mirantis 😩

**Comment by blacktop** [comment]
@Montg0mery I have latest 9 and 10 building/tagging properly now.  I'll try and back fill the others if you think you'd need those? Or we can just move forward now as is?  Also I'll try and get the alpine/beta-nightly via cron/ and bindiff images working soon

**Comment by blacktop** [comment]
So I believe now we'll have 9,10,alpine AND nightly! which will be built once a day.  Feel free to re-open if you see fit or catch anymore bugs/mislabeled images etc

**Comment by Montg0mery** [comment]
> @Montg0mery I have latest 9 and 10 building/tagging properly now. I'll try and back fill the others if you think you'd need those? Or we can just move forward now as is? Also I'll try and get the alpine/beta-nightly via cron/ and bindiff images working soon

I've not tried the alpine images, but for the others, the tags `9`, `10`, and `latest` all seem to point to correct versions now.

Thanks!
