### ISSUE TITLE
Docker Errors

### ISSUE THREAD

**Issue by cameronhopkin** [blacktop/docker-ghidra#2]
docker: Error response from daemon: Mounts denied:
The paths /path/to/projects and /path/to/samples
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

These may need to go to actual paths and be shared in your instructions but about to head to a meetup and getting this error for client

Also getting this error for Server:
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
zsh: command not found: -v

**Comment by blacktop** [comment]
you are not meant to copy/paste the exact example. `/path/to/samples` should not exist on anyone's machine so you read it like a sentence and see you should replace it with a path to your samples.
