### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Martmists-GH** [blacktop/docker-ghidra#25]
Image: `blacktop/ghidra:latest`

command: 
```
$ docker run --init -it --rm \
             --name ghidra-server \
             --cpus 2 \
             --memory 500m \
             -p 13100-13102:13100-13102 \
             -e MAXMEM=500M \
             -e GHIDRA_USERS="mart" \
             -v /opt/ghidra/repos:/repos \
             blacktop/ghidra server
```

<details>
<summary><code>docker logs ghidra-server</code></summary>
<pre><code>GHIDRA_IP: 0.0.0.0
Using service wrapper: yajsw-beta-13.01
Running Ghidra Server...
YAJSW: yajsw-alpha-13.00
OS   : Linux/5.18.3-arch1-1/amd64
JVM  : Oracle Corporation/11.0.15//usr/local/openjdk-11/64
wrapper|YAJSW: yajsw-alpha-13.00
wrapper|OS   : Linux/5.18.3-arch1-1/amd64
wrapper|JVM  : Oracle Corporation/11.0.15//usr/local/openjdk-11/64
system.env 20
env result 20
wrapper|exec:/usr/local/openjdk-11/bin/java -classpath /ghidra/Ghidra/Features/GhidraServer/data/yajsw-beta-13.01/wrapperApp.jar:/ghidra/Ghidra/Features/GhidraServer/data/yajsw-beta-13.01/lib/core/permit/permit-reflect-0.4.jar:/ghidra/Ghidra/Features/GhidraServer/lib/GhidraServer.jar:/ghidra/Ghidra/Framework/FileSystem/lib/FileSystem.jar:/ghidra/Ghidra/Framework/DB/lib/DB.jar:/ghidra/Ghidra/Framework/Docking/lib/Docking.jar:/ghidra/Ghidra/Framework/Generic/lib/Generic.jar:/ghidra/Ghidra/Framework/FileSystem/lib/ganymed-ssh2-262.jar:/ghidra/Ghidra/Framework/Utility/lib/Utility.jar:/ghidra/Ghidra/Framework/Generic/lib/cglib-nodep-2.2.jar:/ghidra/Ghidra/Framework/Generic/lib/guava-19.0.jar:/ghidra/Ghidra/Framework/Generic/lib/jdom-legacy-1.1.3.jar:/ghidra/Ghidra/Framework/Generic/lib/log4j-core-2.17.1.jar:/ghidra/Ghidra/Framework/Generic/lib/log4j-api-2.17.1.jar:/ghidra/Ghidra/Framework/Generic/lib/commons-collections4-4.1.jar:/ghidra/Ghidra/Framework/Generic/lib/commons-lang3-3.9.jar:/ghidra/Ghidra/Framework/Generic/lib/commons-text-1.6.jar:/ghidra/Ghidra/Framework/Generic/lib/commons-io-2.6.jar:/ghidra/Ghidra/Framework/Generic/lib/gson-2.8.9.jar:/ghidra/Ghidra/Framework/Generic/lib/bcpkix-jdk15on-1.69.jar:/ghidra/Ghidra/Framework/Generic/lib/bcprov-jdk15on-1.69.jar:/ghidra/Ghidra/Framework/Generic/lib/bcutil-jdk15on-1.69.jar:/ghidra/Ghidra/Framework/Docking/lib/timingframework-1.0.jar:/ghidra/Ghidra/Framework/Docking/lib/javahelp-2.0.05.jar -Djava.net.preferIPv4Stack=true -DApplicationRollingFileAppender.maxBackupIndex=10 -Dclasspath_frag=/ghidra/server/../Ghidra/Features/GhidraServer/data/classpath.frag -Dghidra.tls.server.protocols=TLSv1.2;TLSv1.3 -Ddb.buffers.DataBuffer.compressedOutput=true -Xms396m -Xmx768m -Djava=/usr/local/openjdk-11/bin/java -Dghidra_home=/ghidra/server/.. -Dwrapper.port=15003 -Dwrapper.key=-4650405481257857489 -Dwrapper.teeName=-4650405481257857489$1655459260584 -Dwrapper.tmp.path=/tmp -Djna_tmpdir=/tmp -Dwrapper.config=/ghidra/server/server.conf org.rzo.yajsw.app.WrapperJVMMain 
wrapper|posix_spawn pid 76
post start false -4650405481257857489$1655459260584
wrapper|started process 76
wrapper|started process with pid 76
76/0|INFO  Using log config file: jar:file:/ghidra/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
76/0|INFO  Using log file: /repos/server.log (LoggingInitialization)  
76/0|INFO  Initializing SSL Context (SSLContextInitializer)  
76/0|INFO  Initializing Random Number Generator... (SecureRandomFactory)  
76/0|INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
76/0|INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
76/0|INFO  Using self-signed certificate: CN=GhidraServer (ApplicationKeyManager)  
76/0|INFO     defaultsigkey: GhidraServer, issued by GhidraServer, S/N 8291b9dccd14decfff99d5f524699539, expires Sun Jun 16 09:47:45 UTC 2024 (ApplicationKeyStore)  
76/0|INFO  Ghidra Server 10.1.4 (GhidraServer)  
76/0|INFO     Server remote access address: 0.0.0.0 (GhidraServer)  
76/0|INFO     Server listening on all interfaces (GhidraServer)  
76/0|INFO     RMI Registry port: 13100 (GhidraServer)  
76/0|INFO     RMI SSL port: 13101 (GhidraServer)  
76/0|INFO     Block Stream port: 13102 (GhidraServer)  
76/0|INFO     Block Stream compression: enabled (GhidraServer)  
76/0|INFO     Root: /repos (GhidraServer)  
76/0|INFO     Auth: Password File (GhidraServer)  
76/0|INFO     Prompt for user ID: yes (GhidraServer)  
76/0|INFO     Anonymous server access: disabled (GhidraServer)  
76/0|INFO     Enabled protocols: TLSv1.2;TLSv1.3 (GhidraServer)  
76/0|INFO  root starting Ghidra Server... (GhidraServer)  
76/0|INFO  Instantiating Repository Manager for /repos (RepositoryManager)  
76/0|INFO  Instantiating User Manager (w/password management) (UserManager)  
76/0|INFO  User file contains 1 entries (UserManager)  
76/0|INFO  Known Users: (UserManager)  
76/0|INFO     mart (UserManager)  
76/0|INFO  Known Repositories: (RepositoryManager)  
76/0|INFO     <none> (RepositoryManager)  
76/0|INFO  Processing 3 queued commands (UserAdmin)  
76/0|INFO  User 'mart' removed (UserAdmin)  
76/0|INFO  User 'mart' added (UserAdmin)  
76/0|INFO  Starting Block Stream Server... (BlockStreamServer)  
76/0|INFO  Registering Ghidra Server... (GhidraServer)  
76/0|INFO  Registered Ghidra Server. (GhidraServer)</code></pre></details>

**Comment by t94j0** [comment]
![Screen Shot 2022-06-18 at 9 59 35 PM](https://user-images.githubusercontent.com/5448134/174466647-6b7a98cc-c97c-48af-b00d-161119aa12cf.png)

Same issue. Ghidra seems to be returning a RST/ACK which is weird. I don't think this is a blacktop/docker-ghidra issue, but an issue with Ghidra itself.

Edit 1: I'm actually requesting port 31001 and port 31002 is being requested, as you can see in the tcp stream. I wonder if Ghidra is automatically incrementing the port number to try to force people to use SSL

Edit 2: 
![Screen Shot 2022-06-18 at 10 36 51 PM](https://user-images.githubusercontent.com/5448134/174467437-9ae5b064-e9fb-47e4-bc44-60b7c20549ab.png)

For me 13100 maps to 30000 and so forth. As you can see, requesting port 30000 actually makes a request to port 30001. Now that 30001 is exposed, it's making a TLS handshake, but still failing. I've tried Ghidra version 10 and 9.2. They both have the same issue.

**Comment by t94j0** [comment]
I'm actually requesting port 31001 and port 31002 is being requested, as you can see in the tcp stream. I wonder if Ghidra is automatically incrementing the port number to try to force people to use SSL

**Comment by blacktop** [comment]
I did update the ghidra server config from master and I think they are trying to force TLS or remove old versions?

**Comment by freshollie** [comment]
Also having this issue. I am a bit confused by your comment @blacktop?

**Comment by entriphy** [comment]
It works after I change `{GHIDRA_IP}` in the `-ip` parameter to my Docker host's IP. Most likely has to do something with that variable.

**Comment by freshollie** [comment]
@entriphy I set the `GHIDRA_IP` env var to my host IP (if that's what you meant) and still didn't work.

I also tried running the container on the host network mode and doing the same (instead of opening the ports)

When I try and conect from ghidra the client just hangs for a few minutes and then errors.

**Comment by blacktop** [comment]
from README:
```bash
$ docker run --init -it --rm \
             --name ghidra-server \
             --cpus 2 \
             --memory 500m \
             -p 13100:13100 \
             -p 13101:13101 \
             -p 13102:13102 \
             -e MAXMEM=500M \
             -e GHIDRA_USERS="root blacktop" \
             -v /path/to/repos:/repos \
             blacktop/ghidra server
```

NOTE the `-p` ports

**Comment by blacktop** [comment]
Other than that I got the same TLS error as you, however, it is just because you haven't let the server finish starting.  Once I gave it a few seconds to finish loading.  Look at the docker logs:
```log
104/0|INFO  Known Repositories: (RepositoryManager)  
104/0|INFO     <none> (RepositoryManager)  
104/0|INFO  Processing 1 queued commands (UserAdmin)  
104/0|INFO  User 'root' added (UserAdmin)  
104/0|INFO  User 'blackop' added (UserAdmin)  
104/0|INFO  Starting Block Stream Server... (BlockStreamServer)  
104/0|INFO  Registering Ghidra Server... (GhidraServer)  
104/0|INFO  Registered Ghidra Server. (GhidraServer)  
```

**Comment by blacktop** [comment]
If that doesn't help feel free to re-open issue.

**Comment by Martmists-GH** [comment]
> Once I gave it a few seconds to finish loading.
I've been waiting for months now and it still hasn't started then, any clue how I could debug this?
