### ISSUE TITLE
Ghidra 10.1.5 released

### ISSUE THREAD

**Issue by Montg0mery** [blacktop/docker-ghidra#26]
As per title :-)

**Comment by Montg0mery** [comment]
@blacktop : thanks. Although I notice that the `latest` tag and the `10.1.4` tag have the same digest at https://registry.hub.docker.com/r/blacktop/ghidra/tags - was there meant to be a 10.1.5 tag instead?

**Comment by blacktop** [comment]
😩 I forgot how to update my own repo...

**Comment by blacktop** [comment]
should be building now, thank you!! ❤️

**Comment by Montg0mery** [comment]
> should be building now, thank you!! heart

That worked, thank you!

**Comment by blacktop** [comment]
oh I guess I need to go back and fix the 10.1.4 tag now, but I understand the issue so I'll re-build the 10.1.4 and then rebuild the 10.1.5 just FYI in case you docker pull in the next 30mins etc
