### ISSUE TITLE
Support ARM Builds

### ISSUE THREAD

**Issue by bman46** [blacktop/docker-ghidra#27]
Would be nice to have ARM64 builds so this can be run on an M1 mac without x64 emulation.

**Comment by blacktop** [comment]
should be building now, not sure how I missed adding this to this image.  Thanks!  NOTE: it's using buildx and qemu, I don't really pay close attention to the docker world anymore, but I'm not 💯 sure that this will also compile ARM versions of the C binaries etc, but it should support the ARM arch w/o having to do emulation?

**Comment by bman46** [comment]
The base images that you use also support arm so it will pull the binaries from there. I believe QEMU is used to build the image as arm on x64. I don't think it is used at all in the resulting images.

**Comment by bman46** [comment]
Actually, I misread that and just realized you are referring to the ghidra binaries, which do not have an included arm version and won't be emulated. Maybe ill add an MR to build the necessary binaries from source and use them.

Edit: this being said, the nightly builds work fine so ill probably use that on arm for now.
