### ISSUE TITLE
10.4 Docker image not updated?

### ISSUE THREAD

**Issue by Montg0mery** [blacktop/docker-ghidra#42]
Hi @blacktop, thanks for updating to 10.4, but it looks like the CI failed to build or push the new image?

https://github.com/blacktop/docker-ghidra/actions/runs/6353755149/job/17259000781

**Comment by blacktop** [comment]
should be fixed now. please check and let me know. thx for the issue!

**Comment by Montg0mery** [comment]
Yes, all good, thank you.
