### ISSUE TITLE
11.2 release

### ISSUE THREAD

**Issue by Montg0mery** [blacktop/docker-ghidra#46]
@blacktop: Hot off the press! https://github.com/NationalSecurityAgency/ghidra/releases

**Comment by blacktop** [comment]
it should be good, but let me know (as there's a new jdk 21 req) if it's good.

**Comment by blacktop** [comment]
ah looks like the first attempt failed, now the fix w/ jdk21 is trying to build now

**Comment by Montg0mery** [comment]
I think the build failed? I don't see an 11.2 tag and the `latest` tag doesn't seem to have updated.

**Comment by blacktop** [comment]
looks like it just built

**Comment by Montg0mery** [comment]
That worked, thanks.
