### ISSUE TITLE
cannot stat 'ghidra_9.1.2': no such file or directory

### ISSUE THREAD

**Issue by jtdavis777** [blacktop/docker-ghidra#6]
In the `Dockerfile`, the zip that is pulled has been renamed to `ghidra_9.1.2_PUBLIC`. The Dockerfile needs to be changed to reflect this.

**Comment by blacktop** [comment]
are you trying to build with the alpine version?

**Comment by jtdavis777** [comment]
I just pulled master and ran Docker build -- the folder name within the ghidra zip caused the build to fail.
